lobo :-
    write("                        ,     ," ), nl,
    write("                        |\\---/|"), nl,
    write("                       /  , ,  |" ), nl,
    write("                  __.-'|  / \\ /)"), nl,
    write("         __ ___.-´        ._./ "), nl,
    write("      .-'  '        :      _/ "), nl,
    write("     / ,    .        .     |" ), nl,
    write("    :  ;    :        :   _/" ), nl,
    write("    |  |   .'     __:   /' "), nl,
    write("    |  :   /'----'| \\  |" ), nl,
    write("    \\  |\\  |      | /| |" ), nl,
    write("     '.'| /       || \\ |" ), nl,
    write("     | /|.'       '.l \\\\_" ), nl,
    write("     || ||             '-'" ), nl,
    write("     '-''-'" ), nl.