papagaio :-
    write('                        .' ), nl,
    write('                         | \/|' ), nl,
    write('(\   _                   ) )|/|' ), nl,
    write('   (/            _----. /.'.'' ), nl,
    write('.-._________..      .' @ _\  .'   ' ), nl,
    write(''.._______.   '.   /    (__| .')), nl,
    write('  '._____.  /   '-/      | _.' ), nl,
    write('   '.______ (         ) ) \), nl,
    write('     '..____ '._       )  )' ), nl,
    write('        .' __.--\  , ,  // (( ), nl,
    write('        '.'  mrf|  \/   ((_.' ), nl,
    write('                '   \ .' ' ), nl,
    write('                 \   (' ), nl,
    write('                  \   '.), nl,
    write('                   \ \ '.)'' ), nl,
    write('                    '-'-' ), nl,
    
